import helpers

# open file, collect content
le_filename = "../inputs/day_22_input.txt"
# le_file_content = helpers.get_file_content_raw(le_filename)
le_lines = helpers.get_file_content_as_lines(le_filename)
# le_char_table = helpers.get_file_content_as_table(le_filename)

######
# PART 1
######

def get_next_secret(secret) :
  MD = 2**24
  MD_MASK = 2**24 - 1
  secret = (secret << 6) ^ secret
  # secret %= MD
  secret &= MD_MASK
  secret = (secret >> 5) ^ secret
  # secret %= MD
  secret &= MD_MASK
  secret = (secret << 11) ^ secret
  # secret %= MD
  secret &= MD_MASK
  return secret

def get_nth_secret(secret_nbr_0, n) :
  next_secret = secret_nbr_0
  for i in range(n) :
    next_secret = get_next_secret(next_secret)
  return next_secret

def compute_sum_of_2000th_secrets(lines) :
  sum = 0
  for line in lines :
    sum += get_nth_secret(int(line), 2000)
  return sum

helpers.print_log_entries("Sum of 2000th number generated by each buyer :",
                          compute_sum_of_2000th_secrets(le_lines), log_cats={"R"})

######
# PART 2
######